name: Python executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:
    - name: Build EXE from Python Script
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: calc.py
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: Windows Build
          path: 
            build.exe

